@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

interface AnnotatedTypeMetadata << interface >>
interface Annotation << interface >>
interface AnnotationMetadata << interface >>
interface ClassMetadata << interface >>
interface MergedAnnotation<A> << interface >>
interface MergedAnnotations << interface >>
interface MethodMetadata << interface >>
class SimpleAnnotationMetadata
class SimpleMethodMetadata
class StandardAnnotationMetadata
class StandardClassMetadata
class StandardMethodMetadata

AnnotationMetadata          -[#008200,plain]-^  AnnotatedTypeMetadata      
AnnotationMetadata          -[#008200,plain]-^  ClassMetadata              
MergedAnnotation            -[#595959,dashed]->  Annotation                 
MethodMetadata              -[#008200,plain]-^  AnnotatedTypeMetadata      
SimpleAnnotationMetadata    -[#008200,dashed]-^  AnnotationMetadata         
SimpleAnnotationMetadata   "1" *-[#595959,plain]-> "annotations\n1" MergedAnnotations          
SimpleAnnotationMetadata   "1" *-[#595959,plain]-> "annotatedMethods\n*" MethodMetadata             
SimpleMethodMetadata       "1" *-[#595959,plain]-> "annotations\n1" MergedAnnotations          
SimpleMethodMetadata        -[#008200,dashed]-^  MethodMetadata             
StandardAnnotationMetadata  -[#008200,dashed]-^  AnnotationMetadata         
StandardAnnotationMetadata "1" *-[#595959,plain]-> "mergedAnnotations\n1" MergedAnnotations          
StandardAnnotationMetadata  -[#000082,plain]-^  StandardClassMetadata      
StandardAnnotationMetadata  -[#595959,dashed]->  StandardMethodMetadata     : "«create»"
StandardClassMetadata       -[#008200,dashed]-^  ClassMetadata              
StandardMethodMetadata     "1" *-[#595959,plain]-> "mergedAnnotations\n1" MergedAnnotations          
StandardMethodMetadata      -[#008200,dashed]-^  MethodMetadata             
@enduml
