@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class ApplicationEvent
class ApplicationStartingEvent
interface ConfigurableBootstrapContext << interface >>
class EventObject
interface Serializable << interface >>
class SpringApplicationEvent

ApplicationEvent              -[#000082,plain]-^  EventObject                  
ApplicationStartingEvent     "1" *-[#595959,plain]-> "bootstrapContext\n1" ConfigurableBootstrapContext 
ApplicationStartingEvent      -[#000082,plain]-^  SpringApplicationEvent       
EventObject                   -[#008200,dashed]-^  Serializable                 
SpringApplicationEvent        -[#000082,plain]-^  ApplicationEvent             
@enduml
